builds:
    - env:
          - CGO_ENABLED=0
      goos:
          - linux

archives:
    - format: binary
checksum:
    name_template: "checksums.txt"
snapshot:
    name_template: "{{ incpatch .Version }}-next"
changelog:
    sort: asc
